/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  async rewrites() {
    return [
      {
        source: "/stats/js/script.js",
        destination: "https://plausible.io/js/script.js",
      },
      {
        source: "/stats/api/event",
        destination: "https://plausible.io/api/event",
      },
      {
        source: "/stats/js/embed.host.js",
        destination: "https://plausible.io/js/embed.host.js",
      },
    ];
  },
  poweredByHeader: false,
  transpilePackages: ["@cobuild/ui"],
  experimental: {
    serverComponentsExternalPackages: ["prisma-database"],
    staleTimes: {
      dynamic: 0,
      static: 180,
    },
  },
  images: {
    imageSizes: [16, 32, 48, 64, 80, 96, 128, 160, 192, 256, 320, 384, 512],
    remotePatterns: [
      { hostname: "*.alchemy.com" },
      { hostname: "alchemy.com" },
      { hostname: "*.cdninstagram.com" },
      { hostname: "cdninstagram.com" },
      { hostname: "*.discord.com" },
      { hostname: "discord.com" },
      { hostname: "*.gnars.com" },
      { hostname: "gnars.com" },
      { hostname: "*.googleusercontent.com" },
      { hostname: "googleusercontent.com" },
      { hostname: "*.imgur.com" },
      { hostname: "imgur.com" },
      { hostname: "*.instagram.com" },
      { hostname: "instagram.com" },
      { hostname: "imagedelivery.net" },
      { hostname: "*.imagedelivery.net" },
      { hostname: "*.ipfs.io" },
      { hostname: "ipfs.io" },
      { hostname: "*.mux.com" },
      { hostname: "mux.com" },
      { hostname: "*.mypinata.cloud" },
      { hostname: "mypinata.cloud" },
      { hostname: "*.nftstorage.link" },
      { hostname: "nftstorage.link" },
      { hostname: "*.openseauserdata.com" },
      { hostname: "openseauserdata.com" },
      { hostname: "*.s3.amazonaws.com" },
      { hostname: "s3.amazonaws.com" },
      { hostname: "*.seadn.io" },
      { hostname: "seadn.io" },
      { hostname: "*.thatsgnar.ly" },
      { hostname: "thatsgnar.ly" },
      { hostname: "*.twimg.com" },
      { hostname: "twimg.com" },
      { hostname: "*.youtube.com" },
      { hostname: "youtube.com" },
      { hostname: "*.zora.co" },
      { hostname: "zora.co" },
      { hostname: "relay.link" },
      { hostname: "*.relay.link" },
      { hostname: "imagedelivery.net" },
      { hostname: "i.ibb.co" },
      { hostname: "*.vimeocdn.com" },
      { hostname: "*.decentralized-content.com" },
      { hostname: "cloudflare-ipfs.com" },
    ],
    dangerouslyAllowSVG: true,
    contentDispositionType: "attachment",
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
